# Generated by Django 5.2.8 on 2025-11-29 03:13

import management.models.media
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(choices=[(1, 'Card 1'), (2, 'Card 2'), (3, 'Card 3')], unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Atividade',
                'verbose_name_plural': '[HOME] Atividades',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('instagram_visible', models.BooleanField(default=False)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('whatsapp_visible', models.BooleanField(default=False)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('twitter_visible', models.BooleanField(default=False)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('facebook_visible', models.BooleanField(default=False)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_visible', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '[HOME] Contato',
                'verbose_name_plural': '[HOME] Contato',
            },
        ),
        migrations.CreateModel(
            name='DepoimentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(choices=[(1, 'Card 1'), (2, 'Card 2'), (3, 'Card 3')], unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Depoimentos',
                'verbose_name_plural': '[HOME] Depoimentos',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='DonateSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_text', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Doação',
                'verbose_name_plural': '[HOME] Doação',
            },
        ),
        migrations.CreateModel(
            name='ManagementMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=management.models.media.upload_media)),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para SEO e acessibilidade.', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Título da mídia (opcional, usado em SEO).', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Legenda curta (opcional).', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
            },
        ),
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_text', models.CharField(max_length=255)),
                ('second_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Missão',
                'verbose_name_plural': '[HOME] Missão',
            },
        ),
        migrations.CreateModel(
            name='PresentationSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('top_text', models.CharField(max_length=255)),
                ('main_text', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Apresentação',
                'verbose_name_plural': '[HOME] Apresentação',
            },
        ),
        migrations.CreateModel(
            name='StatsCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(choices=[(1, 'Card 1'), (2, 'Card 2'), (3, 'Card 3'), (4, 'Card 4')], unique=True)),
                ('stats_number', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Estatística',
                'verbose_name_plural': '[HOME] Estatísticas',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='TributeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Homenagem',
                'verbose_name_plural': '[HOME] Homenagem',
            },
        ),
        migrations.CreateModel(
            name='VolunteerSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('first_text', models.CharField(max_length=500)),
                ('second_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Seja um voluntário',
                'verbose_name_plural': '[HOME] Seja um voluntário',
            },
        ),
    ]
