# Generated by Django 5.2.8 on 2025-11-25 09:29

import django.db.models.deletion
import management.models.media
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testmonial', '0002_alter_depoiment_options_alter_depoiment_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=management.models.media.upload_media)),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para SEO e acessibilidade.', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Título da mídia (opcional, usado em SEO).', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Legenda curta (opcional).', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Gerenciamento - Mídia',
                'verbose_name_plural': 'Gerenciamento - Mídias',
            },
        ),
        migrations.CreateModel(
            name='DepoimentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(choices=[(1, 'Card 1'), (2, 'Card 2'), (3, 'Card 3')], unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('depoiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmonial.depoiment')),
            ],
            options={
                'verbose_name': 'Card de Depoimento da Página Home',
                'verbose_name_plural': 'Cards de Depoimento da Página Home',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('top_text', models.CharField(max_length=255)),
                ('main_text', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia')),
            ],
            options={
                'verbose_name': 'Home - Sessão de Apresentação',
                'verbose_name_plural': 'Home - Sessão de Apresentação',
            },
        ),
    ]
