# Generated by Django 5.2.8 on 2025-11-25 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('instagram_icon', models.BooleanField(default=False)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('whatsapp_icon', models.BooleanField(default=False)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('twitter_icon', models.BooleanField(default=False)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('facebook_icon', models.BooleanField(default=False)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_icon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '[HOME] Contato',
                'verbose_name_plural': '[HOME] Contato',
            },
        ),
        migrations.CreateModel(
            name='DonateSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_text', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Missão',
                'verbose_name_plural': '[HOME] Missão',
            },
        ),
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_text', models.CharField(max_length=255)),
                ('second_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Missão',
                'verbose_name_plural': '[HOME] Missão',
            },
        ),
        migrations.CreateModel(
            name='StatsCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(choices=[(1, 'Card 1'), (2, 'Card 2'), (3, 'Card 3'), (4, 'Card 4')], unique=True)),
                ('stats_number', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[HOME] Estatística',
                'verbose_name_plural': '[HOME] Estatísticas',
                'ordering': ['card_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='depoimentcard',
            options={'ordering': ['card_number'], 'verbose_name': '[HOME] Depoimentos', 'verbose_name_plural': '[HOME] Depoimentos'},
        ),
        migrations.AlterModelOptions(
            name='managementmedia',
            options={'verbose_name': 'Mídia', 'verbose_name_plural': 'Mídias'},
        ),
        migrations.AlterModelOptions(
            name='presentationsection',
            options={'verbose_name': '[HOME] Apresentação', 'verbose_name_plural': '[HOME] Apresentação'},
        ),
        migrations.CreateModel(
            name='TributeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('left_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribute_left_images', to='management.managementmedia')),
                ('right_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribute_right_images', to='management.managementmedia')),
            ],
            options={
                'verbose_name': '[HOME] Homenagem',
                'verbose_name_plural': '[HOME] Homenagem',
            },
        ),
        migrations.CreateModel(
            name='VolunteerSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('first_text', models.CharField(max_length=500)),
                ('second_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia')),
            ],
            options={
                'verbose_name': '[HOME] Seja um voluntário',
                'verbose_name_plural': '[HOME] Seja um voluntário',
            },
        ),
    ]
