# Generated by Django 5.2.8 on 2025-11-29 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('testmonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimentcard',
            name='depoiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmonial.depoiment'),
        ),
        migrations.AddField(
            model_name='activitycard',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia'),
        ),
        migrations.AddField(
            model_name='presentationsection',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia'),
        ),
        migrations.AddField(
            model_name='tributesection',
            name='left_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribute_left_images', to='management.managementmedia'),
        ),
        migrations.AddField(
            model_name='tributesection',
            name='right_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribute_right_images', to='management.managementmedia'),
        ),
        migrations.AddField(
            model_name='volunteersection',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia'),
        ),
    ]
