# Generated by Django 5.2.8 on 2025-11-26 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_contactsection_donatesection_missionsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatesection',
            options={'verbose_name': '[HOME] Doação', 'verbose_name_plural': '[HOME] Doação'},
        ),
        migrations.CreateModel(
            name='ActivityCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(choices=[(1, 'Card 1'), (2, 'Card 2'), (3, 'Card 3')], unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia')),
            ],
            options={
                'verbose_name': '[HOME] Atividade',
                'verbose_name_plural': '[HOME] Atividades',
                'ordering': ['card_number'],
            },
        ),
    ]
