# Generated by Django 5.2.8 on 2025-12-09 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutValueCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(choices=[(1, 'Card 1'), (2, 'Card 2'), (3, 'Card 3'), (4, 'Card 4'), (5, 'Card 5'), (6, 'Card 6'), (7, 'Card 7')], unique=True)),
                ('stats_number', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': '[SOBRE] Valor',
                'verbose_name_plural': '[SOBRE] Valores',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='AboutCarouselSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('medias', models.ManyToManyField(blank=True, related_name='carousel_sections', to='management.managementmedia', verbose_name='Mídias do Carrossel')),
            ],
            options={
                'verbose_name': '[SOBRE] Carrossel',
                'verbose_name_plural': '[SOBRE] Carrossel',
            },
        ),
        migrations.CreateModel(
            name='AboutHistorySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_text', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('background_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_background_images', to='management.managementmedia')),
                ('card_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_card_media', to='management.managementmedia')),
            ],
            options={
                'verbose_name': '[SOBRE] História',
                'verbose_name_plural': '[SOBRE] História',
            },
        ),
        migrations.CreateModel(
            name='AboutIdealizersSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_text', models.CharField(max_length=255)),
                ('idealizers', models.CharField(max_length=255)),
                ('descrption', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia')),
            ],
            options={
                'verbose_name': '[SOBRE] Idealizadores',
                'verbose_name_plural': '[SOBRE] Idealizadores',
            },
        ),
        migrations.CreateModel(
            name='AboutMissionSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_1', models.TextField()),
                ('text_2', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia')),
            ],
            options={
                'verbose_name': '[SOBRE] Missão',
                'verbose_name_plural': '[SOBRE] Missão',
            },
        ),
    ]
