# Generated by Django 5.2.8 on 2025-12-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_aboutvaluecards_aboutcarouselsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvaluecards',
            name='stats_number',
        ),
    ]
