# Generated by Django 5.2.8 on 2025-11-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_donatesection_options_activitycard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycard',
            name='url',
        ),
    ]
