# Generated by Django 5.2.8 on 2025-12-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_aboutvaluecards_stats_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmissionsection',
            name='main_text',
            field=models.CharField(default='Nossa missão', max_length=255),
            preserve_default=False,
        ),
    ]
