# Generated by Django 5.2.8 on 2025-11-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_activitycard_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycard',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activitycard',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
