# Generated by Django 5.2.8 on 2025-11-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_activitycard_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsection',
            old_name='facebook_icon',
            new_name='facebook_visible',
        ),
        migrations.RenameField(
            model_name='contactsection',
            old_name='instagram_icon',
            new_name='instagram_visible',
        ),
        migrations.RenameField(
            model_name='contactsection',
            old_name='twitter_icon',
            new_name='linkedin_visible',
        ),
        migrations.RenameField(
            model_name='contactsection',
            old_name='whatsapp_icon',
            new_name='twitter_visible',
        ),
        migrations.RenameField(
            model_name='contactsection',
            old_name='youtube_icon',
            new_name='whatsapp_visible',
        ),
        migrations.AddField(
            model_name='contactsection',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='youtube_visible',
            field=models.BooleanField(default=False),
        ),
    ]
