# Generated by Django 5.2.8 on 2025-11-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_facebook_icon_contactsection_facebook_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
