# Generated by Django 5.1.8 on 2025-09-03 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=100, verbose_name="Tipo do Evento"),
                ),
                ("event_date", models.DateTimeField(verbose_name="Data do Evento")),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                ("address", models.CharField(max_length=100, verbose_name="Endereço")),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Descrição Curta"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conteúdo do Evento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["title", "-event_date"],
            },
        ),
    ]
