# Generated by Django 5.1.8 on 2025-10-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="is_participation",
            field=models.BooleanField(
                default=False, verbose_name="é obrigatório participação?"
            ),
        ),
    ]
