# Generated by Django 5.1.8 on 2025-09-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="covers/",
                verbose_name="imagem do evento",
            ),
        ),
    ]
