# Generated by Django 5.1.8 on 2025-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_events_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="events",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Endereço"
            ),
        ),
    ]
