# Generated by Django 5.1.8 on 2025-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_events_link_alter_events_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora Do Término do Evento"
            ),
        ),
    ]
