# Generated by Django 5.1.8 on 2025-09-29 20:52

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=management.models.upload_media, verbose_name="Arquivo"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Imagem"), ("video", "Vídeo")],
                        max_length=10,
                        verbose_name="Tipo de Mídia",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção de Mídia",
                "verbose_name_plural": "Seções de Mídia",
            },
        ),
        migrations.CreateModel(
            name="MissionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Primeiro Bloco de Texto"
                    ),
                ),
                (
                    "second_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Segundo Bloco de Texto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção de Missão",
                "verbose_name_plural": "Seções de Missão",
            },
        ),
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Texto de Introdução",
                    ),
                ),
                (
                    "description_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto de Descrição"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_section_images",
                        to="management.mediasection",
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção da Home",
                "verbose_name_plural": "Seções da Home",
            },
        ),
        migrations.CreateModel(
            name="DonationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_section_image",
                        to="management.mediasection",
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção de Doação",
                "verbose_name_plural": "Seções de Doação",
            },
        ),
        migrations.CreateModel(
            name="AgendaSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tema"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agenda_section_image",
                        to="management.mediasection",
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção da Agenda",
                "verbose_name_plural": "Seções da Agenda",
            },
        ),
        migrations.CreateModel(
            name="VoluntarySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voluntary_section_image",
                        to="management.mediasection",
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção de Voluntariado",
                "verbose_name_plural": "Seções de Voluntariado",
            },
        ),
    ]
