# Generated by Django 5.1.8 on 2025-06-19 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendasection",
            options={
                "verbose_name": "seção de Agenda",
                "verbose_name_plural": "seções de Agendas",
            },
        ),
        migrations.AlterModelOptions(
            name="donationsection",
            options={
                "verbose_name": "seção de doação",
                "verbose_name_plural": "seções de doações",
            },
        ),
        migrations.AlterModelOptions(
            name="homesection",
            options={
                "verbose_name": "seção home",
                "verbose_name_plural": "seções da home",
            },
        ),
        migrations.AlterModelOptions(
            name="mediasection",
            options={
                "verbose_name": "seção de mídia",
                "verbose_name_plural": "seções de midias",
            },
        ),
        migrations.AlterModelOptions(
            name="missionsection",
            options={
                "verbose_name": "seção de missão",
                "verbose_name_plural": "seções de missões",
            },
        ),
        migrations.AlterModelOptions(
            name="voluntarysection",
            options={
                "verbose_name": "seção de voluntário",
                "verbose_name_plural": "seções de voluntários",
            },
        ),
    ]
