# Generated by Django 5.1.8 on 2025-06-19 19:54

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_alter_agendasection_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendasection",
            options={
                "verbose_name": "Seção da Agenda",
                "verbose_name_plural": "Seções da Agenda",
            },
        ),
        migrations.AlterModelOptions(
            name="donationsection",
            options={
                "verbose_name": "Seção de Doação",
                "verbose_name_plural": "Seções de Doação",
            },
        ),
        migrations.AlterModelOptions(
            name="homesection",
            options={
                "verbose_name": "Seção da Home",
                "verbose_name_plural": "Seções da Home",
            },
        ),
        migrations.AlterModelOptions(
            name="mediasection",
            options={
                "verbose_name": "Seção de Mídia",
                "verbose_name_plural": "Seções de Mídia",
            },
        ),
        migrations.AlterModelOptions(
            name="missionsection",
            options={
                "verbose_name": "Seção de Missão",
                "verbose_name_plural": "Seções de Missão",
            },
        ),
        migrations.AlterModelOptions(
            name="voluntarysection",
            options={
                "verbose_name": "Seção de Voluntariado",
                "verbose_name_plural": "Seções de Voluntariado",
            },
        ),
        migrations.AlterField(
            model_name="agendasection",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="agendasection",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agenda_section_image",
                to="management.mediasection",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="agendasection",
            name="theme",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tema"
            ),
        ),
        migrations.AlterField(
            model_name="donationsection",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="donationsection",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_section_image",
                to="management.mediasection",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="donationsection",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="homesection",
            name="description_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texto de Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="homesection",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_section_images",
                to="management.mediasection",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="homesection",
            name="intro_text",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Texto de Introdução",
            ),
        ),
        migrations.AlterField(
            model_name="mediasection",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="mediasection",
            name="file",
            field=models.FileField(
                upload_to=management.models.upload_media, verbose_name="Arquivo"
            ),
        ),
        migrations.AlterField(
            model_name="mediasection",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Imagem"), ("video", "Vídeo")],
                max_length=10,
                verbose_name="Tipo de Mídia",
            ),
        ),
        migrations.AlterField(
            model_name="missionsection",
            name="first_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Primeiro Bloco de Texto"
            ),
        ),
        migrations.AlterField(
            model_name="missionsection",
            name="second_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Segundo Bloco de Texto"
            ),
        ),
        migrations.AlterField(
            model_name="voluntarysection",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="voluntarysection",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voluntary_section_image",
                to="management.mediasection",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="voluntarysection",
            name="sub_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Subtítulo"
            ),
        ),
        migrations.AlterField(
            model_name="voluntarysection",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Título"
            ),
        ),
    ]
