# Generated by Django 5.1.8 on 2025-05-30 15:42

import django.db.models.deletion
import testimonial.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=testimonial.models.upload_media)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="depoiment",
            name="function",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="depoiment",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="depoiment",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testimonial_images",
                to="testimonial.mediasection",
            ),
        ),
    ]
