# Generated by Django 5.2.8 on 2025-11-24 11:19

import django.db.models.deletion
import utils.file_utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Depoiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=utils.file_utils.depoiment_image_upload_path, verbose_name='Foto do depoimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depoiments', to='testmonial.function', verbose_name='Funções')),
            ],
            options={
                'verbose_name': 'Depoiment',
                'verbose_name_plural': 'Depoiments',
                'ordering': ['-created_at'],
            },
        ),
    ]
