# Generated by Django 5.2.8 on 2025-11-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depoiment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Depoimento', 'verbose_name_plural': 'Depoimentos'},
        ),
        migrations.AlterField(
            model_name='depoiment',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='depoiment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
