# Generated by Django 5.2.8 on 2025-11-27 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_activitycard_description_and_more'),
        ('testmonial', '0002_alter_depoiment_options_alter_depoiment_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoiment',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='depoiment',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.managementmedia'),
        ),
    ]
