# Generated by Django 5.2.8 on 2025-11-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_shares_count_post_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
