# Generated by Django 5.2.8 on 2025-11-24 11:19

import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_utils.post_cover_image_upload_path, verbose_name='Imagem da capa'),
        ),
    ]
