# Generated by Django 5.1.8 on 2025-11-05 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=False, editable=False, max_length=300, unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("author", "title")},
        ),
    ]
