# Generated by Django 5.2.8 on 2025-11-29 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nome')),
                ('street', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Google Maps')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='Data do Evento')),
                ('event_end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Do Término do Evento')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição Curta')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo do Evento')),
                ('is_participation', models.BooleanField(default=False, verbose_name='é obrigatório participação?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.address', verbose_name='Endereço Completo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['title', '-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventMediaRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Mídia de Evento',
                'verbose_name_plural': 'Mídias de Eventos',
            },
        ),
    ]
