# Generated by Django 5.2.8 on 2025-11-24 11:19

import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_utils.event_image_upload_path, verbose_name='imagem do evento'),
        ),
    ]
