# Generated by Django 5.2.8 on 2025-11-29 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmediarelation',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='management.managementmedia', verbose_name='Mídia'),
        ),
        migrations.AddField(
            model_name='event',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventMediaRelation', to='management.managementmedia', verbose_name='imagens do evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventtype'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmediarelation',
            unique_together={('event', 'media')},
        ),
    ]
