# Generated by Django 5.2.8 on 2025-12-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Evento Online'),
        ),
    ]
