# Generated by Django 5.2.8 on 2025-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_address_eventtype_remove_event_image_event_medias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nome'),
        ),
    ]
