# Generated by Django 5.2.8 on 2025-11-29 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_link_address_name'),
        ('management', '0007_contactsection_to_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMediaRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='events.event', verbose_name='Evento')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='management.managementmedia', verbose_name='Mídia')),
            ],
            options={
                'verbose_name': 'Mídia de Evento',
                'verbose_name_plural': 'Mídias de Eventos',
                'unique_together': {('event', 'media')},
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventMediaRelation', to='management.managementmedia', verbose_name='imagens do evento'),
        ),
    ]
